version: '2'

services:
  app:
    image: 'wg_backend_spring_postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wg_forge_db
      - SPRING_DATASOURCE_USERNAME=wg_forge
      - SPRING_DATASOURCE_PASSWORD=42a

  db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    container_name: db
    ports:
      - "5432:5432"
#    environment:
#      - POSTGRES_USER=wg_forge
#      - POSTGRES_PASSWORD=42a
